name: scp copy folder to remote via SSH

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: parent working directory
        run: pwd
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
            local: /home/runner/work/Zajel-Web/Zajel-Web/dist/
            remote: /home/mylestone/apps/zajel-web
            host: ${{ secrets.HOST }}
            username: ${{ secrets.SSH_USER }}
            privateKey: ${{ secrets.PRIVATE_KEY }}
